name: cheap_learning
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=22.2
  - cudatoolkit=11.1.1
  - torchaudio=0.13.0
  - torchvision=0.14.0

  - pip:
    - transformers[sentencepiece]
    - datasets
    - openprompt
    - pygithub
    - pylint
    - emoji==2.2.0
    
  # Core python
  - numpy
  - tqdm
  - pandas
  - ipykernel
  - requests

  # ML
  - scikit-learn
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn
