name: cheap_learning
channels:
  - conda-forge
  - defaults
  # - pytorch
  # - huggingface

dependencies:
  - python=3.8
  - pip=22.3

  - pip:
    # ML
    # - transformers
    # - torch
    # - openprompt
    - pygithub
    
  # Core python
  - numpy
  - tqdm
  - pandas
  - ipykernel
  - requests

  # ML
  - scikit-learn
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn
