name: cheap_learning
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=22.3

  - pip:
    - torch
    - transformers[sentence_piece]
    - openprompt
    - pygithub
    - pylint
    
  # Core python
  - numpy
  - tqdm
  - pandas
  - ipykernel
  - requests

  # ML
  - scikit-learn
  
  # Plotting
  - matplotlib
  - plotly
  - seaborn
